### ISSUE TITLE
Convert spreadsheet tab contents to JSON

### ISSUE THREAD

**Issue by julia326** [COVID19Tracking/covid-publishing-api#1]
Also make a POST request with that JSON. Toy version can include just the contents of Worksheet 2

**Comment by joshuaellinger** [comment]
I had code available to PULL data  using the Google Python API rather than push from the worksheet so I used that instead.  It is the approach that I've been using on QC for a month.

I have the following concerns about the POST approach for the API:
   1. The data would come in as cells rather than a table/rows.
   2. There is a significant amount of manipulation required before it is usable.
   3. It would require maintaining a bunch of javascript.

My suggestion is that we change the Issue to: "Get working data as JSON from Google  Sheets", declare victory, and move on.  The way it would be consumed is that the Google Sheet hits a rest endpoint that runs the PULL.  The PULL then posts the JSON to the endpoint that updates the DB.

This approach would allow us good separation of concerns and avoid avoid 2-4 days of work without precluding a PUSH approach in the long-run.

**Comment by joshuaellinger** [comment]
Zach showed enough the google sheets code at https://docs.google.com/spreadsheets/d/178b3lMSgzCBtZCxIqBJ8OmnQ9Nm4rWFe3OubnmPsIYg/edit?usp=sharing that it looks like I can easily do the PUSH version.

It would be helpful if we had an endpoint to push to, even if it just discards the payload.

**Comment by joshuaellinger** [comment]
Marking as closed.  Replaced by Issue #13
