### ISSUE TITLE
Spec out API endpoints

### ISSUE THREAD

**Issue by julia326** [COVID19Tracking/covid-publishing-api#33]
These should address the internal/external DB queries as described in the design doc

**Comment by joshuaellinger** [comment]
Don't forget that we need to have stubs for race data even if we don't implement them now.

**Comment by kevee** [comment]
Here are some thoughts that bear on the design of the `GET` features of the internal API.

The new public API is basically a service that fetches data from external sources — including things outside the scope of your work (like volunteers from slack, list of screenshots, press clippings, etc) — and then maps them to field definitions and outputs a *ton* of JSON and CSV files for delivery. It's super-simple, but has a heavy layer of testing and QA work on top.

Because it already does QA, fetching, and file formatting, there is no need for this publishing API to recreate *every* API endpoint. For example, we have endpoints we still have to support like `states/CA/20200304.json` that would be unnecessary for an internal API that is not going to be implemented anywhere else.

We also have endpoints such as `states/CA/current.json` that is merely the most recent value of `states/CA/daily.json`

So I would say you can leave all the slicing-and-dicing of data into endpoints up to the public API builder, and just deliver API endpoints that align in field names with what we have now:

- **State information** - [current](https://covidtracking.com/api/v1/states/info.json) -  A list of all state names and metadata like websites, twitter, etc. 
- **State daily** - [current](https://covidtracking.com/api/v1/states/daily.json) - All daily COVID data about all states.
- **US daily** - [current](https://covidtracking.com/api/v1/us/daily.json) - All daily COVID data on the US
- **Racial data tracker** - There is no current version on this, but I would say still, no need for filtering, a huge JSON object is fine.

**Comment by zachlipton** [comment]
Thanks @kevee, that's really helpful as I've been trying to decide exactly how to delineate the internal API from the public one.  Sticking with clean data and letting the public API worry about the complexities you mentioned to serve the masses sounds like a good plan. We'll also have endpoints that expose history to cover historical changes to the data, but I don't think the public API needs to concern themselves with those initially.

I've been trying toalign the internal API to the external one as much as possible in terms of field names so the project isn't spending a lot of time maintaining multiple mappings. That's something that already started with [the data dictionary](https://docs.google.com/spreadsheets/d/13Lb_qJXwgtx5ySeXf_XyZkod9VAxEPGb3rmj8KUMQ8o/edit#gid=0). For example, the direction I was working with has been to use the `StateInfo` schema you developed consistently: the relevant data is extracted from the spreadsheet and put into a JSON object in `StateInfo` format, that data is put into the `states` table in the db with matching columns, and our `/states` endpoint outputs an array of `StateInfo` objects which the public API knows how to consume. 

There are places where some deviation is necessary—for example, we'll manage timestamps as UTC internally (which leads to questions like do we do the TZ conversion or do you?) and we won't include things like the hashes that are relevant only to the public API. But I think if we both inherit from the same main datatypes and use "allOf" inheritance to add bits specific to the internal and public APIs, that will give the whole project a foundation around a single consistent schema where everything uses the same names. 

Am I overthinking this or does that sound like the right direction? What I'm trying to get away from is what's starting to happen without coordination: a world where we have a Sheet->DB API that calls "California" "stateName," a DB where we store it in a "fullName" column, and a public API that calls it "name." 

Finally, the crazy thought that occurred to me last night, and @careeningspace may hate this, was what if we put the field names directly in the spreadsheet? So below the "Currently 
Hospitalized" header would be a (normally hidden) row that says "hospitalizedCurrently." That would mean the mapping of spreadsheet columns to our One True Names would be right in the spreadsheet, and nobody would need to edit the Apps Script to map new columns (there would still need to be DB and API changes, but one less code change).
 
I'll post a very preliminary API spec for discussion once I've bashed it into shape a little more.

**Comment by careeningspace** [comment]
I am fine with adding table names in a hidden row. Prefer it actually

**Comment by julia326** [comment]
This all sounds good to me! A few thoughts:
- Starting with states info, states daily, US daily in the publishing API is a good first step
- Eventually as we build out the internal API, we may want to move some of the business logic of testing/QA into there. Agnostic on the data slicing/rolling up to US-level, but maaaybe those could go into the internal API also at some point - @kevee what do you think?
- Re: things like timestamps, I think we'd store them in the DB as UTC but we would serve both UTC and (derived) ET fields. SQLAlchemy has easy support for derived fields on DB objects, so things like computing totals and tz conversions can be easily taken care of there

**Comment by zachlipton** [comment]
See https://github.com/COVID19Tracking/covid-api-specs/pull/1 for draft API specification/documentation

**Comment by julia326** [comment]
Fixed in a few PRs.
